defaults:
  - model: 20k
  - _self_

seed: 42
batch_size: 256
total_steps: 1000

data:
  max_digits: 3
  num_samples: null

optimizer:
  _target_: optax.adamw
  learning_rate:
    _target_: optax.cosine_decay_schedule
    init_value: 1e-2
    decay_steps: ${total_steps}
    alpha: 0.1
