learning_rate: 1e-3
flops_per_token: 2920512
params: 1419612

config:
  _target_: tiny.model.Transformer
  n_layers: 7
  d_model: 112
  d_ffw: 448
  n_heads: 14
  n_kv: 14
  vocab_size: 12 # digits 0-9, '+', '='
