learning_rate: 1e-3
flops_per_token: 3245588
params: 1574300

config:
  _target_: tiny.model.Transformer
  n_layers: 9
  d_model: 104
  d_ffw: 416
  n_heads: 13
  n_kv: 13
  vocab_size: 12 # digits 0-9, '+', '='
