learning_rate: 1e-3
flops_per_token: 3360168
params: 1640444

config:
  _target_: tiny.model.Transformer
  n_layers: 11
  d_model: 96
  d_ffw: 384
  n_heads: 12
  n_kv: 12
  vocab_size: 12 # digits 0-9, '+', '='
