learning_rate: 3e-3
flops_per_token: 542172
params: 256572

config:
  _target_: tiny.model.Transformer
  n_layers: 5
  d_model: 56
  d_ffw: 224
  n_heads: 7
  n_kv: 7
  vocab_size: 12 # digits 0-9, '+', '='
