learning_rate: 1e-3
flops_per_token: 6503456
params: 3172172

config:
  _target_: tiny.model.Transformer
  n_layers: 12
  d_model: 128
  d_ffw: 512
  n_heads: 16
  n_kv: 16
  vocab_size: 12 # digits 0-9, '+', '='
