learning_rate: 1e-2
flops_per_token: 171772
params: 79660

config:
  _target_: tiny.model.Transformer
  n_layers: 3
  d_model: 40
  d_ffw: 160
  n_heads: 5
  n_kv: 5
  vocab_size: 12 # digits 0-9, '+', '='
