learning_rate: 3e-3
flops_per_token: 1821636
params: 878892

config:
  _target_: tiny.model.Transformer
  n_layers: 7
  d_model: 88
  d_ffw: 352
  n_heads: 11
  n_kv: 11
  vocab_size: 12 # digits 0-9, '+', '='
