learning_rate: 1e-2
flops_per_token: 414841
params: 190192
total_params: 611392
config:
  _target_: tiny.model.MixtureOfExpertsTransformer
  n_layers: 5
  d_model: 48
  d_ffw: 192
  n_heads: 6
  n_kv: 6
  vocab_size: 12
  n_experts: 4
  k_experts: 1
