learning_rate: 1e-2
flops_per_token: 23082
params: 9252
total_params: 28548
config:
  _target_: tiny.model.MixtureOfExpertsTransformer
  n_layers: 2
  d_model: 16
  d_ffw: 64
  n_heads: 2
  n_kv: 2
  vocab_size: 12
  n_experts: 4
  k_experts: 1
