learning_rate: 3e-3
flops_per_token: 776727
params: 360232
total_params: 1161088
config:
  _target_: tiny.model.MixtureOfExpertsTransformer
  n_layers: 7
  d_model: 56
  d_ffw: 224
  n_heads: 7
  n_kv: 7
  vocab_size: 12
  n_experts: 4
  k_experts: 1
