learning_rate: 1e-3
flops_per_token: 3655578
params: 1753132
total_params: 5674972
config:
  _target_: tiny.model.MixtureOfExpertsTransformer
  n_layers: 10
  d_model: 104
  d_ffw: 416
  n_heads: 13
  n_kv: 13
  vocab_size: 12
  n_experts: 4
  k_experts: 1
