learning_rate: 3e-3
flops_per_token: 662248
params: 303580
total_params: 977500
config:
  _target_: tiny.model.MixtureOfExpertsTransformer
  n_layers: 8
  d_model: 48
  d_ffw: 192
  n_heads: 6
  n_kv: 6
  vocab_size: 12
  n_experts: 4
  k_experts: 1
